[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[[licenses.exceptions]]
crate = "foldhash@0.2.0"
allow = ["Zlib"]

[[licenses.exceptions]]
crate = "icu_collections@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_locale_core@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_normalizer@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_normalizer_data@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_properties@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_properties_data@2.3.0"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "icu_provider@2.3.1"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "litemap@0.8.3"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "potential_utf@0.1.6"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "tinystr@0.8.4"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "unicode-ident@1.0.24"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "writeable@0.6.4"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "webpki-root-certs@1.0.9"
allow = ["CDLA-Permissive-2.0"]

[[licenses.exceptions]]
crate = "yoke@0.8.3"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "yoke-derive@0.8.2"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "zerofrom@0.1.8"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "zerofrom-derive@0.1.7"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "zerotrie@0.2.5"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "zerovec@0.11.8"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "zerovec-derive@0.11.6"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
crate = "jni"
allow = ["MIT", "Apache-2.0"]

[[licenses.exceptions]]
crate = "rustls-platform-verifier"
allow = ["MIT", "Apache-2.0"]
